### ISSUE TITLE
Add Graph decorators

### ISSUE THREAD

**Issue by Glusk** [Glusk/sprouts#57]
Add these Graph decorators:
- `WithEdgePair` - A new graph that **adds** a connection pair (a pair of opposite directed edges to the existing Graph). There should also be an overloaded constructor to pass in the Submove. Origin and direction are enough to build an edge pair.
- `WihtoutEdgePair` - A new graph that **removes** a connection pair (a pair of opposite directed edges to the existing Graph)

**Comment by Glusk2** [comment]
This can only work if Graph objects expose  `Map<Vertex, LocalRotations>` through a getter, which is a really poor design.
