### ISSUE TITLE
Fix gradle build warnings

### ISSUE THREAD

**Issue by Glusk** [Glusk/sprouts#94]
>  ```
> > Configure project : 
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> ```
> The above can be fixed by replacing `compile` with `implementation`. More info here: [link](https://stackoverflow.com/questions/44413952/gradle-implementation-vs-api-configuration).

Fixed in #112.

---

```
warning: [options] bootstrap class path not set in conjunction with -source 1.6
```
Revise `sourceCompatibility` settings in the config files and bump them to `1.8`.

**Comment by Glusk2** [comment]
It's probably best to update the project by `diff`ing with the latest Libgdx Project Generator generated project.

**Comment by Glusk** [comment]
No more `warning: [options] bootstrap class path not set in conjunction with -source 1.6` warnings after the re-write: #205.
